# Generated by Django 2.2 on 2019-04-14 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
