# Generated by Django 2.2 on 2019-04-14 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
